//DO NOT EDIT THIS FILE. Simply use it as a reference.

#include <string>

using namespace std;

class Wallet{
	public:
		int* bills;
		string owners_name;

		//constructor
		Wallet(int* bills, string owners_name);

        //calculates the total amount stored in the wallet
		int calc_amount();

        //prints out the owners name and how many of each bill they have in their wallet
		void print();

        //changes the bills array to have the same dollar amount, but with as few bills
        //as possible (if the wallet had 5 $1 bills, it would change that to be 1 $5 bill
        //and so on).
		void reduce();
};