# Simply execute "make" in working directory to create executable "hw4"
# Running "make clean" will remove the executable

# Deleting the # sign at the end of line 10 and renaming the additional files
# to whatever you have named them will let you compile more than 1 file

# PLEASE TEST YOUR MAKEFILE TO ENSURE IT WORKS BEFORE SUBMITTING

all:
	g++ -std=c++11 -g -o hw4 main.cpp points.cpp points.h
clean:
	rm hw4
